[theme]
primaryColor = "#081ae5"        # your accent color
backgroundColor = "#ffffff"     # main background
secondaryBackgroundColor = "#f0f0f0"  # sidebar background
textColor = "#060606"           # text color

[browser]
gatherUsageStats = false

[client]
showSidebarNavigation = true